# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: bean-fast-thanh

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore "./BeanFastApi/BeanFastApi.csproj"
    - name: Build
      run: dotnet build --no-restore "./BeanFastApi/BeanFastApi.csproj"
    - name: Test
      run: dotnet test --no-build --verbosity normal "./BeanFastApi/BeanFastApi.csproj"
