name: dotnet-cd
on:
  workflow_run:
    workflows: ["dotnet-ci"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo systemctl restart api
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
